language: java
install: true
sudo: true
cache:
    directories:
        - $HOME/.gradle
        - .gradle/
        - testfixtures/offline-repo/build/root

matrix:
    include:
        - jdk: openjdk11
        - os: osx

stages:
    - quality
    - check
    - report

jobs:
    include:
      - stage: quality
        script: ./gradlew --console=plain license
        name: 'Licensing'
      - script: ./gradlew --console=plain codenarcAll
        name: 'Coding style'
      - stage: check
        name: 'Build and test'
        script: ./gradlew --console=plain --scan test intTest remoteTest gradleTest jacocoRootReport
        after_success: ./gradlew coveralls
