name: Push documentation
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Combine documentation
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: docs
          arguments: --console=plain -q combineDocs
      - name: Publish documentation
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: docs
          arguments: "--console=plain --info :antora:publishDocs :gh-pages:publishDocs
          -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GITHUB_PUBLISH_USER }}
          -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_PUBLISH_KEY }}
          -Dorg.ajoberstar.grgit.auth.force=hardcoded"
