name: Push documentation
on:
  push:
    branches:
      - master
      - development-4.x
permissions:
  contents: write
jobs:
  push-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'asciidoctor/asciidoctor-gradle-plugin'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Combine documentation
        run: |
          cd docs
          ./gradlew --console=plain -q combineDocs
      - name: Publish documentation
        env:
          CI_BRANCH: ${{ github.ref_name }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          GRGIT_USER: 'GH Action User'
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          ./gradlew --console=plain :gh-pages:publishDocs --info --stacktrace
